# SwiftLint Configuration
# Only lint Sources/ and Tests/ directories

included:
  - Sources
  - Tests

type_name:
  allowed_symbols: ["_"]
identifier_name:
  allowed_symbols: ["_"]
  min_length:
    2
  excluded:
    - Description
    - Topics
    - Previews
    - Code
    - Links
    - Embeds
    - Children
    - Preview
line_length:
  warning: 200
  error: 240
file_length:
  warning: 400
  error: 500
type_body_length:
  warning: 250
  error: 350
disabled_rules:
  - trailing_comma
  - trailing_whitespace