type_name:
  allowed_symbols: ["_"]
identifier_name:
  allowed_symbols: ["_"]
  min_length:
    2
  excluded:
    - Description
    - Topics
    - Previews
    - Code
    - Links
    - Embeds
    - Children
    - Preview
line_length:
  warning: 200
  error: 240